//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YAF.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Install {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Install() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YAF.App_GlobalResources.Install", typeof(Install).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email Adress.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the name of the super user.
        /// </summary>
        public static string AdminName {
            get {
                return ResourceManager.GetString("AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string AdminPassword {
            get {
                return ResourceManager.GetString("AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verify Password.
        /// </summary>
        public static string AdminPassword2 {
            get {
                return ResourceManager.GetString("AdminPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the name of the new Board.
        /// </summary>
        public static string BoardName {
            get {
                return ResourceManager.GetString("BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Config Password.
        /// </summary>
        public static string ConfigPassword {
            get {
                return ResourceManager.GetString("ConfigPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection Details.
        /// </summary>
        public static string ConnectionDetails {
            get {
                return ResourceManager.GetString("ConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Existing Connection String.
        /// </summary>
        public static string ConnectionExist {
            get {
                return ResourceManager.GetString("ConnectionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select SQL Server Database Connection String:.
        /// </summary>
        public static string ConnectionExistDesc {
            get {
                return ResourceManager.GetString("ConnectionExistDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to connect:.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create New Connection String.
        /// </summary>
        public static string ConnectionNew {
            get {
                return ResourceManager.GetString("ConnectionNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection String will be saved as .
        /// </summary>
        public static string ConnectionNewNote {
            get {
                return ResourceManager.GetString("ConnectionNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection Succeeded.
        /// </summary>
        public static string ConnectionSuccess {
            get {
                return ResourceManager.GetString("ConnectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database Connection Test.
        /// </summary>
        public static string ConnectionTest {
            get {
                return ResourceManager.GetString("ConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create New Board.
        /// </summary>
        public static string CreateBoard {
            get {
                return ResourceManager.GetString("CreateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Config Password.
        /// </summary>
        public static string CreatePassword {
            get {
                return ResourceManager.GetString("CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Since this is the first time you install or upgrade this version of the forum, you need to create a configuration password for security..
        /// </summary>
        public static string CreatePasswordText {
            get {
                return ResourceManager.GetString("CreatePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create New Super User (Host).
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current Version: .
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the Data Source (Name or address of the sql server).
        /// </summary>
        public static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YAF.NET Database Connection.
        /// </summary>
        public static string DBConnection {
            get {
                return ResourceManager.GetString("DBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the Database Name.
        /// </summary>
        public static string DBName {
            get {
                return ResourceManager.GetString("DBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A username for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username already exists. Please enter a different user name..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the Config Password.
        /// </summary>
        public static string EnterConfigPassword {
            get {
                return ResourceManager.GetString("EnterConfigPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the configuration password to upgrade or manually install the forum..
        /// </summary>
        public static string EnterConfigPasswordDesc {
            get {
                return ResourceManager.GetString("EnterConfigPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Board is already installed..
        /// </summary>
        public static string ErrorBoardInstalled {
            get {
                return ResourceManager.GetString("ErrorBoardInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a Board name..
        /// </summary>
        public static string ErrorBoardName {
            get {
                return ResourceManager.GetString("ErrorBoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must update your appSettings with the YAF.ConfigPassword Key to continue. NOTE: The key name is case sensitive..
        /// </summary>
        public static string ErrorConfigPassword {
            get {
                return ResourceManager.GetString("ErrorConfigPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a Board email address..
        /// </summary>
        public static string ErrorForumEmail {
            get {
                return ResourceManager.GetString("ErrorForumEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter a password..
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create Admin User Failed:.
        /// </summary>
        public static string ErrorUserCreate {
            get {
                return ResourceManager.GetString("ErrorUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter the super user email address..
        /// </summary>
        public static string ErrorUserEmail {
            get {
                return ResourceManager.GetString("ErrorUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must enter the super user user name,.
        /// </summary>
        public static string ErrorUserName {
            get {
                return ResourceManager.GetString("ErrorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Existing user name is invalid and does not represent a current user in the membership store..
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You entered the &lt;strong&gt;wrong password&lt;/strong&gt;!.
        /// </summary>
        public static string ErrorWrongPassword {
            get {
                return ResourceManager.GetString("ErrorWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use Existing DB Connection String.
        /// </summary>
        public static string ExistConnection {
            get {
                return ResourceManager.GetString("ExistConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use Existing User.
        /// </summary>
        public static string ExistingUser {
            get {
                return ResourceManager.GetString("ExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the name of the existing user to make super user (host).
        /// </summary>
        public static string ExistingUserName {
            get {
                return ResourceManager.GetString("ExistingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clicking Finish will take you to the Forum main page..
        /// </summary>
        public static string FinishDesc {
            get {
                return ResourceManager.GetString("FinishDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forum Email Address.
        /// </summary>
        public static string ForumEmail {
            get {
                return ResourceManager.GetString("ForumEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forum Base Url Mask.
        /// </summary>
        public static string ForumUrl {
            get {
                return ResourceManager.GetString("ForumUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the from Email Address.
        /// </summary>
        public static string FromEmail {
            get {
                return ResourceManager.GetString("FromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your forum is now been ready..
        /// </summary>
        public static string InitFinish {
            get {
                return ResourceManager.GetString("InitFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialize.
        /// </summary>
        public static string Initialize {
            get {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use Integrated Security.
        /// </summary>
        public static string Integrated {
            get {
                return ResourceManager.GetString("Integrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail (SMTP) Sending Test.
        /// </summary>
        public static string MailTest {
            get {
                return ResourceManager.GetString("MailTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sends a test Message to the Email address that is defined as Send to address.
        /// </summary>
        public static string MailTestDesc {
            get {
                return ResourceManager.GetString("MailTestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Write Access to App Settings.
        /// </summary>
        public static string ManuallyPassword {
            get {
                return ResourceManager.GetString("ManuallyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click &quot;Next&quot; when you are ready..
        /// </summary>
        public static string ManuallyPasswordDesc {
            get {
                return ResourceManager.GetString("ManuallyPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to modify your config file to write the installation password due to a permission issue..
        /// </summary>
        public static string ManuallyPasswordError {
            get {
                return ResourceManager.GetString("ManuallyPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Migrate Roles and Users.
        /// </summary>
        public static string Migrate {
            get {
                return ResourceManager.GetString("Migrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  user(s) found in your forum database..
        /// </summary>
        public static string MigrateCount {
            get {
                return ResourceManager.GetString("MigrateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click &quot;Next&quot; to start the upgrade (migration) of all roles and users from your old Yet Another Forum.NET database to the .NET Provider Model..
        /// </summary>
        public static string MigrateDesc {
            get {
                return ResourceManager.GetString("MigrateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The migration task can take a &lt;strong&gt;very&lt;/strong&gt; long time depending on how many users are in your forum..
        /// </summary>
        public static string MigrateNote {
            get {
                return ResourceManager.GetString("MigrateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable Migration (not recommended).
        /// </summary>
        public static string MigrateSkip {
            get {
                return ResourceManager.GetString("MigrateSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Migrating Users....
        /// </summary>
        public static string MigrateUsers {
            get {
                return ResourceManager.GetString("MigrateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please do not navigate away from this page while the migration is in progress. It can take a very long time to perform the migration..
        /// </summary>
        public static string MigrateUsersText {
            get {
                return ResourceManager.GetString("MigrateUsersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create New DB Connection String.
        /// </summary>
        public static string NewConnection {
            get {
                return ResourceManager.GetString("NewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clicking &quot;Next&quot; will initialize your database to the latest version..
        /// </summary>
        public static string NextInitDb {
            get {
                return ResourceManager.GetString("NextInitDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click &quot;Next&quot; when you are ready..
        /// </summary>
        public static string NextReady {
            get {
                return ResourceManager.GetString("NextReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clicking &quot;Next&quot; will upgrade your database to the latest version..
        /// </summary>
        public static string NextUpgradeDb {
            get {
                return ResourceManager.GetString("NextUpgradeDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NO.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Write Access to Settings.
        /// </summary>
        public static string NoWriteAppSettings {
            get {
                return ResourceManager.GetString("NoWriteAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to modify your config file to set Database Connection due to no write permission..
        /// </summary>
        public static string NoWriteAppSettingsNote {
            get {
                return ResourceManager.GetString("NoWriteAppSettingsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Write Access to Database Connection Strings.
        /// </summary>
        public static string NoWriteConnSettings {
            get {
                return ResourceManager.GetString("NoWriteConnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to modify your config file to set Database Connection string due to no write permission..
        /// </summary>
        public static string NoWriteConnSettingsNote {
            get {
                return ResourceManager.GetString("NoWriteConnSettingsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please open the .
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на file in the application root directory and add/update the following key in the &amp;lt;AppSettings&amp;gt; section:.
        /// </summary>
        public static string OpenFileDesc {
            get {
                return ResourceManager.GetString("OpenFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на file in the application root directory and add/update the following key in the &amp;lt;connectionStrings&amp;gt; section:.
        /// </summary>
        public static string OpenFileDesc2 {
            get {
                return ResourceManager.GetString("OpenFileDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This password is stored with your appSettings in the file....
        /// </summary>
        public static string PasswordFile {
            get {
                return ResourceManager.GetString("PasswordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verification is not the same as your password..
        /// </summary>
        public static string PasswordNoMatch {
            get {
                return ResourceManager.GetString("PasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YAF.NET Has Write Access to Root Application Directory (&quot;~/&quot;) ....
        /// </summary>
        public static string PermissionApp {
            get {
                return ResourceManager.GetString("PermissionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YAF.NET Has Write Access to &quot;~/Upload&quot; directory ....
        /// </summary>
        public static string PermissionUpload {
            get {
                return ResourceManager.GetString("PermissionUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Re-Enter the Config Password.
        /// </summary>
        public static string ReenterConfigPassword {
            get {
                return ResourceManager.GetString("ReenterConfigPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The answer to the security question.
        /// </summary>
        public static string SecurityAnswer {
            get {
                return ResourceManager.GetString("SecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The question you will be asked when you need to retrieve your lost password.
        /// </summary>
        public static string SecurityQuestion {
            get {
                return ResourceManager.GetString("SecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The email sending appears to be working from your YAF installation..
        /// </summary>
        public static string SmtpTestBody {
            get {
                return ResourceManager.GetString("SmtpTestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SMTP Test Details.
        /// </summary>
        public static string SmtpTestDetails {
            get {
                return ResourceManager.GetString("SmtpTestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test Email From Yet Another Forum.NET.
        /// </summary>
        public static string SmtpTestSubject {
            get {
                return ResourceManager.GetString("SmtpTestSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail Sent. Verify it&apos;s received at your entered email address..
        /// </summary>
        public static string SmtpTestSuccess {
            get {
                return ResourceManager.GetString("SmtpTestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the SQL Password.
        /// </summary>
        public static string SqlPass {
            get {
                return ResourceManager.GetString("SqlPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the SQL User Name.
        /// </summary>
        public static string SqlUser {
            get {
                return ResourceManager.GetString("SqlUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test Connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test Smtp Settings.
        /// </summary>
        public static string TestEmail {
            get {
                return ResourceManager.GetString("TestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test Permission.
        /// </summary>
        public static string TestPermission {
            get {
                return ResourceManager.GetString("TestPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test Settings.
        /// </summary>
        public static string TestSettings {
            get {
                return ResourceManager.GetString("TestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click the &quot;Previous&quot; button to edit the database configuration..
        /// </summary>
        public static string TestSettingsDesc {
            get {
                return ResourceManager.GetString("TestSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You may want to test your YAF configuration settings here before proceeding..
        /// </summary>
        public static string TestSettingsText {
            get {
                return ResourceManager.GetString("TestSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Guest User Time Zone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the to Email Address.
        /// </summary>
        public static string ToEmail {
            get {
                return ResourceManager.GetString("ToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unchecked.
        /// </summary>
        public static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upgrade.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upgrade BBCode Extensions and Spam Words.
        /// </summary>
        public static string UpgradeExtensions {
            get {
                return ResourceManager.GetString("UpgradeExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your forum has now been upgraded to the latest version..
        /// </summary>
        public static string UpgradeFinish {
            get {
                return ResourceManager.GetString("UpgradeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If this is an upgrade, please enter the configuration password you created when the forum was first installed, not the admin user password..
        /// </summary>
        public static string UpgradeNote {
            get {
                return ResourceManager.GetString("UpgradeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upgrade Version: .
        /// </summary>
        public static string UpgradeVersion {
            get {
                return ResourceManager.GetString("UpgradeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Validate Permissions.
        /// </summary>
        public static string ValidatePermission {
            get {
                return ResourceManager.GetString("ValidatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YetAnotherForum.NET Installation is easier when the Application has write access to your .config
        ///                        files..
        /// </summary>
        public static string ValidatePermissionDesc {
            get {
                return ResourceManager.GetString("ValidatePermissionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click below to test if permissions are correct. If they are not, you can
        ///                        still use the installation wizard..
        /// </summary>
        public static string ValidatePermissionText {
            get {
                return ResourceManager.GetString("ValidatePermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are about to upgrade YAF.NET to the most recent version. Before proceeding with upgrade process please ensure that...
        ///                        &lt;ul&gt;
        ///                            &lt;li&gt;you created a backup of your existing installation&lt;/li&gt;
        ///                        &lt;/ul&gt;.
        /// </summary>
        public static string WarningUpgrade {
            get {
                return ResourceManager.GetString("WarningUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to the YAF.NET Installation.
        /// </summary>
        public static string WelcomeInstall {
            get {
                return ResourceManager.GetString("WelcomeInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click &quot;Next&quot; to start the Install process..
        /// </summary>
        public static string WelcomeInstallDesc {
            get {
                return ResourceManager.GetString("WelcomeInstallDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This Installer will guide you through the steps required to Install YetAnotherForum.NET (YAF.NET)..
        /// </summary>
        public static string WelcomeInstallText {
            get {
                return ResourceManager.GetString("WelcomeInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to the YAF.NET Upgrade Process.
        /// </summary>
        public static string WelcomeUpgrade {
            get {
                return ResourceManager.GetString("WelcomeUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click &quot;Next&quot; to start the Upgrade process..
        /// </summary>
        public static string WelcomeUpgradeDesc {
            get {
                return ResourceManager.GetString("WelcomeUpgradeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YES.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
